# Generated by Django 3.0.8 on 2020-07-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="clientes_photos"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
